services:
  - type: web
    name: analise-de-opcoes
    runtime: python
    plan: free
    repo: https://github.com/dhonne86/Analise-de-Op-es.git
    branch: main
    buildCommand: ""
    startCommand: "python app.py"
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.9
      - key: FREE_OPLAB_BASE
        value: https://opcoes.oplab.com.br
